import * as path from 'node:path';
import type { BundleMetadata, Violation } from '../types.js';

export interface MarkdownContext {
  bundle?: BundleMetadata;
  rootForDisplay?: string;
  filesScanned: number;
  pluginsActive: Array<{ id: string; name: string }>;
  toolVersion: string;
  scannedAt: string;
}

export function formatMarkdown(violations: Violation[], ctx: MarkdownContext): string {
  const lines: string[] = [];
  lines.push(header(ctx));
  lines.push('');
  lines.push(summary(violations, ctx));
  lines.push('');
  if (violations.length === 0) {
    lines.push('No issues found.');
    lines.push('');
  } else {
    lines.push('---');
    lines.push('');
    lines.push(...bodyByLocaleThenPlugin(violations, ctx));
  }
  lines.push('---');
  lines.push('');
  lines.push(...methodology(ctx));
  return lines.join('\n');
}

function header(ctx: MarkdownContext): string {
  if (ctx.bundle) {
    const { name, version, build, bundleId } = ctx.bundle;
    return `# locale-lint audit: ${name} ${version} (${build}) — ${bundleId}`;
  }
  const label = ctx.rootForDisplay ? path.basename(ctx.rootForDisplay) : 'source tree';
  return `# locale-lint audit: ${label}`;
}

function summary(violations: Violation[], ctx: MarkdownContext): string {
  const locales = new Set<string>();
  const plugins = new Set<string>();
  for (const v of violations) {
    locales.add(v.variantExpected);
    plugins.add(v.pluginId);
  }
  const localesList = [...locales].sort().join(', ') || '(none)';
  const localesNote =
    locales.size > 0 ? ` (${localesList})` : '';
  return `Scanned **${ctx.filesScanned}** \`.strings\` file${ctx.filesScanned === 1 ? '' : 's'}. Found **${violations.length}** issue${violations.length === 1 ? '' : 's'} across **${plugins.size}** plugin${plugins.size === 1 ? '' : 's'}${localesNote}.`;
}

function bodyByLocaleThenPlugin(
  violations: Violation[],
  ctx: MarkdownContext,
): string[] {
  const byLocale = new Map<string, Violation[]>();
  for (const v of violations) {
    const list = byLocale.get(v.variantExpected) ?? [];
    list.push(v);
    byLocale.set(v.variantExpected, list);
  }
  const out: string[] = [];
  for (const locale of [...byLocale.keys()].sort()) {
    out.push(`## ${locale}`);
    out.push('');
    const localeViolations = byLocale.get(locale)!;
    const byPlugin = new Map<string, Violation[]>();
    for (const v of localeViolations) {
      const list = byPlugin.get(v.pluginId) ?? [];
      list.push(v);
      byPlugin.set(v.pluginId, list);
    }
    for (const pluginId of [...byPlugin.keys()].sort()) {
      const pluginViolations = byPlugin.get(pluginId)!;
      out.push(`### ${pluginId} (${pluginViolations.length} finding${pluginViolations.length === 1 ? '' : 's'})`);
      out.push('');
      for (const v of pluginViolations) {
        out.push(`- \`${displayPath(v.file, ctx)}:${v.line}:${v.col}\` (key \`${v.key}\`)`);
        out.push(`  ${v.message}`);
      }
      out.push('');
    }
  }
  return out;
}

function methodology(ctx: MarkdownContext): string[] {
  const out: string[] = [];
  out.push('## Methodology');
  out.push('');
  out.push(`Generated by \`locale-lint\` v${ctx.toolVersion} from <https://github.com/digitalby/zh-lint>.`);
  if (ctx.pluginsActive.length > 0) {
    const plugins = ctx.pluginsActive.map((p) => `\`${p.id}\``).join(', ');
    out.push(`Plugins active: ${plugins}.`);
  }
  out.push(`Scanned at: ${ctx.scannedAt}.`);
  out.push('');
  out.push(
    'This report only inspects unencrypted localization resources (\`.strings\` files). It does not decrypt, modify, or redistribute any portion of the app bundle. Verify findings against the linked Apple references before acting on them.',
  );
  return out;
}

function displayPath(absPath: string, ctx: MarkdownContext): string {
  if (ctx.rootForDisplay && absPath.startsWith(ctx.rootForDisplay)) {
    const rel = path.relative(ctx.rootForDisplay, absPath);
    return rel === '' ? path.basename(absPath) : rel;
  }
  return absPath;
}
